-- RotaFlow schema. Run with `supabase db push` after linking a project.
create type public.app_role as enum ('admin','shipment','security','goods_acceptance','regional');
create type public.shipment_status as enum ('waiting','called','arrived','at_ramp','shipped','not_delivered');

create table public.regions (id uuid primary key default gen_random_uuid(), name text not null unique, code text not null unique, city text not null, distance_km integer not null default 0 check(distance_km >= 0), estimated_minutes integer not null default 0 check(estimated_minutes >= 0), created_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role app_role not null default 'shipment', region_id uuid references public.regions(id), created_at timestamptz not null default now(), check((role = 'regional' and region_id is not null) or (role <> 'regional' and region_id is null)));
create table public.suppliers (id uuid primary key default gen_random_uuid(), name text not null unique, contact_name text, phone text, active boolean not null default true, created_at timestamptz not null default now());
create table public.drivers (id uuid primary key default gen_random_uuid(), supplier_id uuid references public.suppliers(id), full_name text not null, phone text, license_plate text not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.shipments (id uuid primary key default gen_random_uuid(), plate text not null, supplier_id uuid references public.suppliers(id), driver_id uuid references public.drivers(id), origin_region_id uuid not null references public.regions(id), destination_region_id uuid not null references public.regions(id), status shipment_status not null default 'waiting', pallets integer not null default 0 check(pallets >= 0), crates integer not null default 0 check(crates >= 0), notes text not null default '', created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(origin_region_id <> destination_region_id));
create table public.shipment_status_history (id bigint generated always as identity primary key, shipment_id uuid not null references public.shipments(id) on delete cascade, from_status shipment_status, to_status shipment_status not null, note text not null default '', changed_by uuid not null references public.profiles(id), changed_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), recipient_id uuid not null references public.profiles(id) on delete cascade, shipment_id uuid references public.shipments(id) on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create index shipments_status_idx on public.shipments(status); create index shipments_destination_idx on public.shipments(destination_region_id); create index notifications_recipient_idx on public.notifications(recipient_id, created_at desc);

create function public.current_profile() returns public.profiles language sql stable security definer set search_path=public as $$ select * from public.profiles where id=auth.uid() $$;
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;
create function public.shipment_visible(origin_id uuid,destination_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and (p.role <> 'regional' or p.region_id in(origin_id,destination_id))) $$;
create function public.valid_status_change(old_status shipment_status,new_status shipment_status) returns boolean language sql stable as $$ select case (select role from public.profiles where id=auth.uid()) when 'admin' then true when 'security' then (old_status,new_status) in (('waiting','called'),('called','arrived')) when 'shipment' then (old_status,new_status) in (('called','at_ramp'),('arrived','at_ramp'),('at_ramp','shipped'),('waiting','not_delivered')) when 'goods_acceptance' then (old_status,new_status) in (('shipped','arrived'),('arrived','not_delivered')) when 'regional' then (old_status,new_status) in (('waiting','shipped'),('arrived','shipped')) else false end $$;

alter table public.regions enable row level security; alter table public.profiles enable row level security; alter table public.suppliers enable row level security; alter table public.drivers enable row level security; alter table public.shipments enable row level security; alter table public.shipment_status_history enable row level security; alter table public.notifications enable row level security;
create policy "authenticated read regions" on public.regions for select to authenticated using(true);
create policy "authenticated read suppliers" on public.suppliers for select to authenticated using(true);
create policy "authenticated read drivers" on public.drivers for select to authenticated using(true);
create policy "profiles self or admin read" on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy "admin manages profiles" on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "visible shipment read" on public.shipments for select to authenticated using(public.shipment_visible(origin_region_id,destination_region_id));
create policy "authorized shipment create" on public.shipments for insert to authenticated with check(created_by=auth.uid() and exists(select 1 from public.profiles p where p.id=auth.uid() and (p.role in('admin','shipment') or (p.role='regional' and p.region_id in(origin_region_id,destination_region_id)))));
create policy "authorized shipment update" on public.shipments for update to authenticated using(public.shipment_visible(origin_region_id,destination_region_id)) with check(public.shipment_visible(origin_region_id,destination_region_id));
create policy "visible history read" on public.shipment_status_history for select to authenticated using(exists(select 1 from public.shipments s where s.id=shipment_id and public.shipment_visible(s.origin_region_id,s.destination_region_id)));
create policy "own notification read" on public.notifications for select to authenticated using(recipient_id=auth.uid()); create policy "own notification update" on public.notifications for update to authenticated using(recipient_id=auth.uid()) with check(recipient_id=auth.uid());

create function public.audit_shipment_change() returns trigger language plpgsql security definer set search_path=public as $$ begin if old.status <> new.status then if not public.valid_status_change(old.status,new.status) then raise exception 'Role is not permitted to change status from % to %',old.status,new.status; end if; insert into shipment_status_history(shipment_id,from_status,to_status,note,changed_by) values(new.id,old.status,new.status,new.notes,auth.uid()); insert into notifications(recipient_id,shipment_id,title,body) select p.id,new.id,'Vehicle status updated',new.plate||' vehicle: '||new.status from profiles p where p.id<>auth.uid() and (p.role='admin' or (new.status='called' and p.role='shipment') or (new.status='waiting' and p.role='security') or (p.role='regional' and p.region_id in(new.origin_region_id,new.destination_region_id))); end if; new.updated_at=now(); return new; end $$;
create trigger shipment_change_guard before update on public.shipments for each row execute function public.audit_shipment_change();
alter publication supabase_realtime add table public.shipments, public.notifications;
